# Generated by Django 2.0.3 on 2019-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190217_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='static/default_avatar.png', upload_to='profile_avatar'),
        ),
    ]
