# Generated by Django 2.1.3 on 2019-03-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_auto_20190217_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=70, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('preview_pic', models.ImageField(default='staticfiles/default_game_preview.png', upload_to='preview_pic')),
                ('link', models.URLField(unique=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_games', related_query_name='game', to='authentication.Account')),
                ('owners', models.ManyToManyField(related_name='owned_games', related_query_name='game', to='authentication.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderBoard', related_query_name='score', to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerScores', related_query_name='score', to='authentication.Account')),
            ],
        ),
    ]
