# Generated by Django 2.1.3 on 2019-03-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('shooter', 'Shooter'), ('fighting', 'Fighting'), ('platformer', 'Platformer'), ('survival', 'Survival'), ('rpg', 'Role-playing'), ('strategy', 'Strategy'), ('sports', 'Sports'), ('racing', 'Racing'), ('party', 'Party'), ('educational', 'Educational')], max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=70, unique=True),
        ),
    ]
